In [10]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
import copy
import seaborn as sns
sns.set()

In [11]:
data = pd.read_csv('../Data/all_in_one.csv')
data.Datetime = pd.to_datetime(data.Datetime)
data.head()

,Datetime,temp,desc,templow,icon,baro,wind,wd,hum,rain,...,intensite_greve,etat_barre_ce,q_ce,k_ce,etat_barre_lc,q_lc,k_lc,etat_barre_pv,q_pv,k_pv
0,2014-01-01 00:00:00,7.0,Low clouds.,6.0,17.0,1011.0,15.0,220.0,92.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2014-01-01 01:00:00,6.0,Low clouds.,6.0,17.0,1011.0,15.0,220.0,92.0,0.0,...,0.9,3.0,4.0,0.00000,3.0,205.0,2.25945,3.0,486.0,6.17889
2,2014-01-01 02:00:00,6.0,Low clouds.,6.0,17.0,1011.0,15.0,220.0,92.0,0.0,...,0.9,3.0,21.0,0.10445,3.0,283.0,3.25111,3.0,571.0,6.66222
3,2014-01-01 03:00:00,6.0,Low clouds.,6.0,17.0,1011.0,15.0,220.0,92.0,0.0,...,0.9,3.0,417.0,6.12667,3.0,309.0,3.36000,3.0,532.0,5.56611
4,2014-01-01 04:00:00,6.0,Low clouds.,6.0,17.0,1011.0,15.0,220.0,92.0,0.0,...,0.9,3.0,1089.0,14.39890,3.0,277.0,3.01445,3.0,458.0,4.63444

In [12]:
data = data[data.Datetime < '2020-12-08']

# Missing values

In [13]:
data.at[data.desc=='No weather data available', ['temp', 'templow', 'icon', 'baro', 'wind', 'wd','hum', 'rain', 'fog', 'thunder', 'snow']] = np.nan

In [14]:
for col in ['temp', 'templow', 'icon', 'baro', 'wind', 'wd','hum', 'rain', 'fog', 'thunder', 'snow']:
    data[col] = data[col].interpolate(method='linear')

In [15]:
data[data.desc=='No weather data available']

,Datetime,temp,desc,templow,icon,baro,wind,wd,hum,rain,...,intensite_greve,etat_barre_ce,q_ce,k_ce,etat_barre_lc,q_lc,k_lc,etat_barre_pv,q_pv,k_pv
984,2014-02-11 00:00:00,17.000000,No weather data available,16.285714,12.142857,1025.285714,8.142857,52.857143,74.857143,0.0,...,0.0,3.0,762.0,4.09000,3.0,204.0,2.00500,3.0,307.0,3.08611
985,2014-02-11 01:00:00,16.500000,No weather data available,15.571429,11.285714,1023.571429,9.285714,75.714286,77.714286,0.0,...,0.0,3.0,562.0,3.25500,3.0,105.0,1.13889,3.0,223.0,2.53056
986,2014-02-11 02:00:00,16.000000,No weather data available,14.857143,10.428571,1021.857143,10.428571,98.571429,80.571429,0.0,...,0.0,3.0,360.0,3.42222,3.0,72.0,0.79833,3.0,164.0,1.80445
987,2014-02-11 03:00:00,15.500000,No weather data available,14.142857,9.571429,1020.142857,11.571429,121.428571,83.428571,0.0,...,0.0,3.0,255.0,2.64000,3.0,43.0,0.53611,3.0,102.0,1.08778
988,2014-02-11 04:00:00,15.000000,No weather data available,13.428571,8.714286,1018.428571,12.714286,144.285714,86.285714,0.0,...,0.0,3.0,198.0,1.82056,3.0,34.0,0.37000,3.0,64.0,0.79834
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
55459,2020-04-29 19:00:00,12.857143,No weather data available,12.285714,9.857143,1005.142857,20.428571,224.285714,77.142857,0.0,...,0.0,3.0,361.0,9.38111,3.0,385.0,2.54889,3.0,181.0,2.23000
55460,2020-04-29 20:00:00,12.285714,No weather data available,11.428571,11.285714,1004.714286,20.142857,221.428571,79.714286,0.0,...,0.0,3.0,315.0,7.66222,3.0,381.0,2.27222,3.0,170.0,1.99889
55461,2020-04-29 21:00:00,11.714286,No weather data available,10.571429,12.714286,1004.285714,19.857143,218.571429,82.285714,0.0,...,0.0,3.0,301.0,4.60445,3.0,391.0,2.70500,3.0,183.0,2.01500
55462,2020-04-29 22:00:00,11.142857,No weather data available,9.714286,14.142857,1003.857143,19.571429,215.714286,84.857143,0.0,...,0.0,3.0,168.0,2.36556,3.0,315.0,1.86722,3.0,131.0,1.49167
55463,2020-04-29 23:00:00,10.571429,No weather data available,8.857143,15.571429,1003.428571,19.285714,212.857143,87.428571,0.0,...,0.0,3.0,84.0,0.72445,3.0,169.0,1.04723,3.0,60.0,0.91278

In [16]:
data.to_csv('../Data/fillna_big_df.csv', index=False)